### PR TITLE
Null safety

### PR DESCRIPTION
**Pull request by tshedor**
### :sparkles: What kind of change does this PR introduce? (Bug fix, feature, docs update...)

Migrate's to [Dart's null safety](https://dart.dev/null-safety/migration-guide)

### :arrow_heading_down: What is the current behavior?

No sound null safety

### :new: What is the new behavior (if this is a feature change)?

Sound null safety

### :boom: Does this PR introduce a breaking change?

Enforces Dart 2.12 as the minimum Dart SDK

### :thinking: Checklist before submitting

- [x] All projects build
- [x] Follows style guide lines ([code style guide](https://github.com/ninjasolutions/flutter_pusher/blob/master/CONTRIBUTING.md))
- [x] Relevant documentation was updated
- [x] Rebased onto current develop

### CODE REVIEW

**Review by genert — APPROVED** [review]
LGTM

**Comment by tshedor** [comment]
@genert will you merge this in?

**Comment by tshedor** [comment]
@genert hey, are you going to release this?

**Comment by devbrandonlong** [comment]
hi @genert. would it be possible to move forward with @tshedor's change?

**Comment by Josiassejod1** [comment]
Would love if you could get this merged @genert

**Comment by tshedor** [comment]
Hey @genert could you please merge this PR?

**Comment by tshedor** [comment]
@genert can you please merge this

**Comment by hann-1** [comment]
Hi @genert , can you merge this PR? a million thanks!

**Comment by daniel7byte** [comment]
Hello, please merge! We need Null Safety 🙏
@tshedor @genert

**Comment by tshedor** [comment]
If I could merge this I genuinely would.

**Comment by tshedor** [comment]
@genert Could you please merge this or let me maintain this repo?

**Comment by Josiassejod1** [comment]
@genert can we get this merged please ?

**Pull request merged**
